import { injectState } from '../../slapp/injectState';

// views convert services in a flat object that is easy to operate in React components

class EditorService {

  state = injectState({
    activeSceneId: '',
    activeItemId: '',
  });

  resetSelection() {
    // call autogenerated mutation
    this.state.setActiveItemId(1);
  }

}




// inside component
function EditorComponent() {
  const { resetSelection, activeItemId } = useService(EditorService);


  // activeItemId is reactive
  // resetSelection is async action

  return (
    <div>
      Selected item is { activeItemId }
      <button onClick={resetSelection}> Reset Selection </button>
    </div>
  )
}

// inside another service
function doSomethingWithEditor() {

  const serviceView = createServiceView(EditorService);

}
