// inspired by ReactQuery

import { injectQuery } from '../../slapp/query';
import { useService } from '../../_plugins/useService';

class EditorService {

  itemsQuery = injectQuery('https://api-url/items.json', []);

}

function EditorComponent() {

  const { items } = useService(EditorService); // items is an autogenerated variable

  return (
    <div>
      { items.map(item => <div>{item.name}</div>)}
    </div>
  );
}

// select more autogenerated variables
function EditorComponent2() {

  const {
    items,
    itemsLoading,
    itemsError,
    itemsRefetch,
  } = useService(EditorService);

  if (itemsLoading) return 'Loading...';

  if (itemsError) return (
    <button>
      Failed to load items
      <button onClick={itemsRefetch}>Retry</button>
    </div>
  );

  return (
    <div>
      { items.map(item => <div>{item.name}</div>)}
    </div>
  );
}
